name: Code Review with code-review-gpt

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的 Git 历史记录

      # Step 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 根据项目需求调整版本

      # Step 3: 安装 Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Step 4: 添加 Bun 到 PATH
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Step 5: 安装依赖
      - name: Install dependencies
        run: bun add code-review-gpt@latest
      # Step 6: 运行代码审查脚本
      - name: Run Code Review Script
        run: |
          bun run code-review-gpt review \
            --reviewType costOptimized \
            --debug \
            --commentPerFile true \
            --ci github
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # 自动提供的 GitHub Token
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: "SimbaKingjoe/helloworld"
          BASE_SHA: $(git merge-base origin/main HEAD)
          GITHUB_SHA: $(git rev-parse HEAD)
